[package]
name = "confucius"
version = "0.5.2"
description = "本地 Markdown 编辑器"
authors = ["renfy"]
edition = "2021"

[lib]
name = "confucius_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
tauri-plugin-process = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
walkdir = "2"
notify = "7"
base64 = "0.22"
tokio = { version = "1", features = ["full"] }
